// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace demanda_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825185606_PgiaFase0Fundacao")]
    partial class PgiaFase0Fundacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.AreaDemandante", b =>
                {
                    b.Property<int>("AreaDemandanteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AreaDemandanteID"));

                    b.Property<string>("NM_DEMANDANTE")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NM_SIGLA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AreaDemandanteID");

                    b.ToTable("AreaDemandantes");
                });

            modelBuilder.Entity("Models.AreaExecutora", b =>
                {
                    b.Property<int>("AreaExecutoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AreaExecutoraId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AreaExecutoraId");

                    b.ToTable("AreasExecutoras");
                });

            modelBuilder.Entity("Models.Demanda", b =>
                {
                    b.Property<int>("demandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("demandaId"));

                    b.Property<int?>("AREA_DEMANDANTEAreaDemandanteID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("EsteiraId")
                        .HasColumnType("uuid");

                    b.Property<string>("NM_PROJETO")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NR_PROCESSO_SEI")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("demandaId");

                    b.HasIndex("AREA_DEMANDANTEAreaDemandanteID");

                    b.HasIndex("EsteiraId");

                    b.ToTable("Demandas", (string)null);
                });

            modelBuilder.Entity("Models.Esteira", b =>
                {
                    b.Property<Guid>("EsteiraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCentralIT")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EsteiraId");

                    b.ToTable("Esteiras");
                });

            modelBuilder.Entity("Models.Etapa", b =>
                {
                    b.Property<int>("EtapaProjetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EtapaProjetoId"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("DT_FIM")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DT_INICIO")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NM_ETAPA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NM_PROJETOdemandaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PERCENT_EXECUTADO")
                        .HasColumnType("numeric");

                    b.Property<int?>("ResponsavelAreaExecutoraId")
                        .HasColumnType("integer");

                    b.Property<string>("TIPO_ENTREGA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EtapaProjetoId");

                    b.HasIndex("NM_PROJETOdemandaId");

                    b.HasIndex("ResponsavelAreaExecutoraId");

                    b.ToTable("Etapas");
                });

            modelBuilder.Entity("Models.Pgia.PgiaAgenteInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("CargoFuncao")
                        .HasColumnType("text")
                        .HasColumnName("cargo_funcao");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<string>("Vinculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("vinculo");

                    b.HasKey("UserId")
                        .HasName("pk_pgia_agente_info");

                    b.ToTable("pgia_agente_info", null, t =>
                        {
                            t.HasCheckConstraint("ck_pgia_agente_info_vinculo", "vinculo IN ('Servidor efetivo','Comissionado','Estagiário','Prestador de serviço')");
                        });
                });

            modelBuilder.Entity("Models.Pgia.PgiaEncarregadoDados", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("agente_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateOnly>("AtoData")
                        .HasColumnType("date")
                        .HasColumnName("ato_data");

                    b.Property<string>("AtoNumero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ato_numero");

                    b.Property<string>("AtoTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ato_tipo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<DateOnly>("DataComunicacaoSgdi")
                        .HasColumnType("date")
                        .HasColumnName("data_comunicacao_sgdi");

                    b.Property<DateOnly?>("FimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fim_vigencia");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("inicio_vigencia");

                    b.Property<long>("OrgaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("orgao_id");

                    b.Property<string>("ProcessoSeiComunicacao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("processo_sei_comunicacao");

                    b.HasKey("Id")
                        .HasName("pk_pgia_encarregado_dados");

                    b.HasIndex("AgenteId")
                        .HasDatabaseName("ix_pgia_encarregado_agente");

                    b.HasIndex("OrgaoId")
                        .IsUnique()
                        .HasDatabaseName("ux_pgia_encarregado_vigente")
                        .HasFilter("ativo");

                    b.ToTable("pgia_encarregado_dados", (string)null);
                });

            modelBuilder.Entity("Models.Pgia.PgiaOrgao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("NaturezaJuridica")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("natureza_juridica");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<bool?>("PrestaServicoCidadao")
                        .HasColumnType("boolean")
                        .HasColumnName("presta_servico_cidadao");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sigla");

                    b.Property<Guid?>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_pgia_orgao");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("ux_pgia_orgao_sigla");

                    b.HasIndex("UnidadeId")
                        .IsUnique()
                        .HasDatabaseName("ux_pgia_orgao_unidade");

                    b.ToTable("pgia_orgao", null, t =>
                        {
                            t.HasCheckConstraint("ck_pgia_orgao_natureza", "natureza_juridica IN ('Administração direta','Autarquia','Fundação pública','Empresa pública','Sociedade de economia mista')");

                            t.HasCheckConstraint("ck_pgia_orgao_servico_cidadao", "natureza_juridica IN ('Empresa pública','Sociedade de economia mista') OR presta_servico_cidadao IS NULL");
                        });
                });

            modelBuilder.Entity("Models.Pgia.PgiaPrazoConformidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("BaseLegal")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("base_legal");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<DateOnly?>("CumpridoEm")
                        .HasColumnType("date")
                        .HasColumnName("cumprido_em");

                    b.Property<DateOnly>("DataLimite")
                        .HasColumnType("date")
                        .HasColumnName("data_limite");

                    b.Property<string>("Obrigacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obrigacao");

                    b.Property<long?>("OrgaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("orgao_id");

                    b.HasKey("Id")
                        .HasName("pk_pgia_prazo_conformidade");

                    b.HasIndex("OrgaoId", "DataLimite")
                        .HasDatabaseName("ix_pgia_prazo_orgao");

                    b.ToTable("pgia_prazo_conformidade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BaseLegal = "arts. 10, § 1º e 35, I",
                            CriadoEm = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLimite = new DateOnly(2026, 8, 2),
                            Obrigacao = "Designar e comunicar à SGDI o Responsável de IA"
                        },
                        new
                        {
                            Id = 2L,
                            BaseLegal = "art. 35, I",
                            CriadoEm = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLimite = new DateOnly(2026, 8, 2),
                            Obrigacao = "Designar e comunicar à SGDI o Encarregado de Dados"
                        },
                        new
                        {
                            Id = 3L,
                            BaseLegal = "arts. 10, II e 35, II",
                            CriadoEm = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLimite = new DateOnly(2026, 10, 1),
                            Obrigacao = "Elaborar e remeter o inventário inicial de sistemas de IA"
                        },
                        new
                        {
                            Id = 4L,
                            BaseLegal = "arts. 29, § único e 35, III",
                            CriadoEm = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLimite = new DateOnly(2026, 12, 30),
                            Obrigacao = "Incluir as trilhas ProCapIA/DF no plano de capacitação"
                        },
                        new
                        {
                            Id = 5L,
                            BaseLegal = "art. 37",
                            CriadoEm = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLimite = new DateOnly(2026, 12, 30),
                            Obrigacao = "Revisar e adequar atos e contratos anteriores ao decreto"
                        },
                        new
                        {
                            Id = 6L,
                            BaseLegal = "art. 35, IV",
                            CriadoEm = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLimite = new DateOnly(2027, 7, 3),
                            Obrigacao = "Concluir e publicar as AIA dos sistemas de Alto Risco em operação"
                        },
                        new
                        {
                            Id = 7L,
                            BaseLegal = "art. 26, § 3º",
                            CriadoEm = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLimite = new DateOnly(2026, 12, 30),
                            Obrigacao = "SGDI: elaborar o Guia de Contratações de IA, aprovado pelo CGTIC"
                        },
                        new
                        {
                            Id = 8L,
                            BaseLegal = "art. 33, caput",
                            CriadoEm = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLimite = new DateOnly(2027, 3, 31),
                            Obrigacao = "SGDI: publicar o Relatório Anual de Governança de IA"
                        });
                });

            modelBuilder.Entity("Models.Pgia.PgiaResponsavelIa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AcumulaFuncaoTic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acumula_funcao_tic");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("agente_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateOnly>("AtoData")
                        .HasColumnType("date")
                        .HasColumnName("ato_data");

                    b.Property<string>("AtoNumero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ato_numero");

                    b.Property<string>("AtoTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ato_tipo");

                    b.Property<bool?>("CapacitacaoAdequada")
                        .HasColumnType("boolean")
                        .HasColumnName("capacitacao_adequada");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<DateOnly>("DataComunicacaoSgdi")
                        .HasColumnType("date")
                        .HasColumnName("data_comunicacao_sgdi");

                    b.Property<DateOnly?>("FimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fim_vigencia");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("inicio_vigencia");

                    b.Property<long>("OrgaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("orgao_id");

                    b.Property<string>("ProcessoSeiComunicacao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("processo_sei_comunicacao");

                    b.HasKey("Id")
                        .HasName("pk_pgia_responsavel_ia");

                    b.HasIndex("AgenteId")
                        .HasDatabaseName("ix_pgia_responsavel_ia_agente");

                    b.HasIndex("OrgaoId")
                        .IsUnique()
                        .HasDatabaseName("ux_pgia_responsavel_ia_vigente")
                        .HasFilter("ativo");

                    b.ToTable("pgia_responsavel_ia", (string)null);
                });

            modelBuilder.Entity("app.Models.Unidade", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("app.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakId")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PapelPgia")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("Unidadeid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Unidadeid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Demanda", b =>
                {
                    b.HasOne("Models.AreaDemandante", "AREA_DEMANDANTE")
                        .WithMany()
                        .HasForeignKey("AREA_DEMANDANTEAreaDemandanteID");

                    b.HasOne("Models.Esteira", "Esteira")
                        .WithMany()
                        .HasForeignKey("EsteiraId");

                    b.Navigation("AREA_DEMANDANTE");

                    b.Navigation("Esteira");
                });

            modelBuilder.Entity("Models.Etapa", b =>
                {
                    b.HasOne("Models.Demanda", "NM_PROJETO")
                        .WithMany("Entregaveis")
                        .HasForeignKey("NM_PROJETOdemandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.AreaExecutora", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelAreaExecutoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NM_PROJETO");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Models.Pgia.PgiaAgenteInfo", b =>
                {
                    b.HasOne("app.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Models.Pgia.PgiaAgenteInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pgia_agente_info_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Pgia.PgiaEncarregadoDados", b =>
                {
                    b.HasOne("app.Models.User", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pgia_encarregado_agente");

                    b.HasOne("Models.Pgia.PgiaOrgao", "Orgao")
                        .WithMany()
                        .HasForeignKey("OrgaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pgia_encarregado_orgao");

                    b.Navigation("Agente");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("Models.Pgia.PgiaOrgao", b =>
                {
                    b.HasOne("app.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pgia_orgao_unidade");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Models.Pgia.PgiaPrazoConformidade", b =>
                {
                    b.HasOne("Models.Pgia.PgiaOrgao", "Orgao")
                        .WithMany()
                        .HasForeignKey("OrgaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_pgia_prazo_orgao");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("Models.Pgia.PgiaResponsavelIa", b =>
                {
                    b.HasOne("app.Models.User", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pgia_responsavel_ia_agente");

                    b.HasOne("Models.Pgia.PgiaOrgao", "Orgao")
                        .WithMany()
                        .HasForeignKey("OrgaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pgia_responsavel_ia_orgao");

                    b.Navigation("Agente");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("app.Models.User", b =>
                {
                    b.HasOne("app.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("Unidadeid");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Models.Demanda", b =>
                {
                    b.Navigation("Entregaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
