// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace demanda_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220001123_ReestruturaEntregaveis")]
    partial class ReestruturaEntregaveis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.AreaDemandante", b =>
                {
                    b.Property<int>("AreaDemandanteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AreaDemandanteID"));

                    b.Property<string>("NM_DEMANDANTE")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NM_SIGLA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AreaDemandanteID");

                    b.ToTable("AreaDemandantes");
                });

            modelBuilder.Entity("Models.AreaExecutora", b =>
                {
                    b.Property<int>("AreaExecutoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AreaExecutoraId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AreaExecutoraId");

                    b.ToTable("AreasExecutoras");
                });

            modelBuilder.Entity("Models.Demanda", b =>
                {
                    b.Property<int>("demandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("demandaId"));

                    b.Property<int?>("AREA_DEMANDANTEAreaDemandanteID")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EsteiraId")
                        .HasColumnType("uuid");

                    b.Property<string>("NM_PROJETO")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NR_PROCESSO_SEI")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("demandaId");

                    b.HasIndex("AREA_DEMANDANTEAreaDemandanteID");

                    b.HasIndex("EsteiraId");

                    b.ToTable("Demandas", (string)null);
                });

            modelBuilder.Entity("Models.Esteira", b =>
                {
                    b.Property<Guid>("EsteiraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EsteiraId");

                    b.ToTable("Esteiras");
                });

            modelBuilder.Entity("Models.Etapa", b =>
                {
                    b.Property<int>("EtapaProjetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EtapaProjetoId"));

                    b.Property<DateTime>("DT_FIM")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DT_INICIO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NM_ETAPA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NM_PROJETOdemandaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PERCENT_EXECUTADO")
                        .HasColumnType("numeric");

                    b.Property<int?>("ResponsavelAreaExecutoraId")
                        .HasColumnType("integer");

                    b.Property<string>("TIPO_ENTREGA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EtapaProjetoId");

                    b.HasIndex("NM_PROJETOdemandaId");

                    b.HasIndex("ResponsavelAreaExecutoraId");

                    b.ToTable("Etapas");
                });

            modelBuilder.Entity("app.Models.Unidade", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("app.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("Unidadeid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Unidadeid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Demanda", b =>
                {
                    b.HasOne("Models.AreaDemandante", "AREA_DEMANDANTE")
                        .WithMany()
                        .HasForeignKey("AREA_DEMANDANTEAreaDemandanteID");

                    b.HasOne("Models.Esteira", "Esteira")
                        .WithMany()
                        .HasForeignKey("EsteiraId");

                    b.Navigation("AREA_DEMANDANTE");

                    b.Navigation("Esteira");
                });

            modelBuilder.Entity("Models.Etapa", b =>
                {
                    b.HasOne("Models.Demanda", "NM_PROJETO")
                        .WithMany("Entregaveis")
                        .HasForeignKey("NM_PROJETOdemandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.AreaExecutora", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelAreaExecutoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NM_PROJETO");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("app.Models.User", b =>
                {
                    b.HasOne("app.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("Unidadeid");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Models.Demanda", b =>
                {
                    b.Navigation("Entregaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
