name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
jobs:
  build:
    runs-on: self-hosted   

    steps:
    - name: Deploy com docker-compose
      run: | 
        cd ..
        docker-compose down
        docker-compose up --build -d
