name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
jobs:
  build:
    

    runs-on: self-hosted   

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build da imagem
      run: |
        docker build -f Dockerfile.prod -t ${{ secrets.DOCKERHUB_USERNAME }}/sgpd_service:latest .

    - name: Push da imagem
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/sgpd_service:latest 

    - name: Deploy com docker-compose
      run: | 
        cd ..
        docker-compose down
        docker-compose up --build -d
